import create_database
import create_populate_CAT2
import create_populate_Hipparcos_completo
import create_populate_CAT1_and_CAT1_intersec_HIP_not_in_CAT2_and_CAT1_not_in_Simbad
import create_populate_CAT1_product
import create_populate_CAT2_product
import create_populate_CAT2_DR1_DR2_DR3

create_database
create_populate_CAT2
create_populate_Hipparcos_completo
create_populate_CAT1_and_CAT1_intersec_HIP_not_in_CAT2_and_CAT1_not_in_Simbad
create_populate_CAT1_product
create_populate_CAT2_product
create_populate_CAT2_DR1_DR2_DR3
